### ISSUE TITLE
Update check list for c# 9

### ISSUE THREAD

**Issue by initram** [tree-sitter/tree-sitter-c-sharp#108]
The following features do not need changes to the syntax:
- Module initializers (is just a new attribute)
- Skip localsinit (is just a new attribute)
- Extension GetEnumerator (Allow extention methods with the right signature to be automatically used in foreach loops)

I don't know if we should remove them from the list or just check them off, as there should be nothing for us to implement. They are all semantic changes to the language.

**Comment by damieng** [comment]
It's really so people can know what thing we are/are not supporting until we hit 100% (or get very close). I can check them off.
