### ISSUE TITLE
Gap list?

### ISSUE THREAD

**Issue by frankshearar** [tree-sitter/tree-sitter-c-sharp#11]
Is there a list of constructs etc. not yet supported?

**Comment by damieng** [comment]
It's basically the "expressions" used in statement blocks - they're kind of tricky as they're going to rely on order of precedence and that doesn't come out of the Roslyn specs.

Another area is switch based pattern matching.

I'll put together a bunch of issues with help required so break up the remaining work.

**Comment by damieng** [comment]
Various help wanted issues have been created and more are coming to track the gap.

**Comment by maxbrunsfeld** [comment]
Also, there is now [a list of repos](https://github.com/tree-sitter/tree-sitter-c-sharp/blob/c701915adecb98b1c44c3e744600aeca4a1d2a4f/script/fetch-examples#L17-L18) that we are striving to parse 100% of without error, and [a list of filenames that contain parse errors](https://github.com/tree-sitter/tree-sitter-c-sharp/blob/master/script/known-failures.txt). The file that parses these repos is [`script/parse-examples`](https://github.com/tree-sitter/tree-sitter-c-sharp/blob/master/script/parse-examples).

So one productive workflow is to just go through the `known-failures` list one at a time, and use the `tree-sitter parse` output to figure out what syntactic constructs are not parsing successfully. For each one of those, you could add a unit test in the `corpus` folder and modify the grammar to make it parse.
