### ISSUE TITLE
Conditional access pattern failure

### ISSUE THREAD

**Issue by damieng** [tree-sitter/tree-sitter-c-sharp#131]
This kind of `if` pattern is not working in the case of 

```csharp
if ((me as Person)?._Age != 1)
{
}
```

This looks like it could be to do with the priority of `conditional_access_expression`.

**Comment by initram** [comment]
I think there are multiple things that are going wrong here. One of them is that we allow real_literals to start with under-score before a number, changing the rules for integer_literal and real_literal helps a bit. Here is the code I have tried:
`    integer_literal: $ => token(seq(
      choice(
        (/[0-9][0-9_]*/), // Decimal
        (/0[xX][0-9a-fA-F_]+/), // Hex
        (/0[bB][01_]+/) // Binary
      ),
      optional(/u|U|l|L|ul|UL|uL|Ul|lu|LU|Lu|lU/)
    )),

    null_literal: $ => 'null',

    real_literal: $ => {
      const suffix = /[fFdDmM]/;
      const exponent = /[eE][+-]?[0-9_]+/;
      return token(choice(
        seq(
          (/[0-9][0-9_]*/),
          '.',
          (/[0-9][0-9_]*/),
          optional(exponent),
          optional(suffix)
        ),
        seq(
          '.',
          (/[0-9][0-9_]*/),
          optional(exponent),
          optional(suffix)
        ),
        seq(
          (/[0-9][0-9_]*/),
          exponent,
          optional(suffix)
        ),
        seq(
          (/[0-9][0-9_]*/),
          suffix
        )
      ))
    },`

Then it should parse, but the precedence is wrong. It interpreted it kind of like this:

`if ((me as Person)?((._Age) != 1))
{
}`

**Comment by damieng** [comment]
I've put up a fix for the literals at #132 - it's a bit different as it turns out that literals should also not end with `_` either.

**Comment by initram** [comment]
we should also make sure that the precedence is right for `var c = (char)(me as string)?[1];`, `var c = !(me as Person)?.IsOld;`, `var c = await (me as Person)?.SomethingAsync();`

I am currently trying to solve some of these issues, but I may create a pull request that only fixes a subset to begin with.

**Comment by damieng** [comment]
I've been hacking on this as well - there's definitely more than one problem here - even regular `conditional_expressions` are incorrect, e.g.

```csharp
var a = b ? 1 + 2 : 3;
```

Is generating:
```
(equals_value_clause
  (conditional_expression
    (identifier)
    (binary_expression (integer_literal) (integer_literal)) (integer_literal))
```

When it should be generating

```
...
(equals_value_clause
  (conditional_expression
    (member_access_expression (identifier) (identifier))
    (string_literal) (string_literal))))))))
```
I'll raise another issue for that tho. I suspect the problems are related.

**Comment by damieng** [comment]
Here's two test cases and the expected results I've been trying to get working FWIW:

```
=====================================
Conditional access expression with member binding
=====================================

if (a?.B != 1) { }

---

(compilation_unit
  (global_statement
    (if_statement
      (binary_expression
        (conditional_access_expression (identifier) (member_binding_expression (identifier)))
        (integer_literal))
      (block))))

=====================================
Conditional access expression with simple member access
=====================================
      
if ((p as Person[])?[0]._Age != 1) { }

---

(compilation_unit
  (global_statement
    (if_statement
      (binary_expression
          (conditional_access_expression
            (parenthesized_expression
              (binary_expression (identifier) (array_type (identifier) (array_rank_specifier))))
              (member_access_expression
                (element_binding_expression
                  (bracketed_argument_list (argument (integer_literal))))
            (identifier)))
        (integer_literal))
      (block))))
```

**Comment by initram** [comment]
I think we are going to have trouble implementing this correctly, as it is really hard to get the following to parse correctly:

`var a = s ? A() : B();` this needs to parse as conditional_expression
`var a = s ? .A();` this needs to parse as conditional_access_expression as the question mark is followed by a dot (even though it is not part of the syntax fot the conditional_access_expression)

Maybe we can do something funky with multiple precedence values like in nullable_type, but this is kind of beyond my understanding of tree-sitter.

**Comment by damieng** [comment]
Yeah I was running into problems with conditional_expression and conditional_access_expression messing with each other. The latter should be parsing as conditional_access_expression as it doesn't have the `:` required by conditional_expression but I also saw it go down this route.

I also tried combining the rules into one conditional type but that failed in different ways.

**Comment by damieng** [comment]
What's also annoying is the C# proposal for `?.` and co have a very different syntax tree/parse names that don't at all match up with whatever Roslyn is doing (also not documented).

**Comment by initram** [comment]
We could also implement it in a different way than roslyn. Otherwise I think we will need some kind of non-capturing lookahead feature in tree sitter.
