### ISSUE TITLE
IEnumerator<T>-derived struct finds method named "IEnumerator" and non-generic interfaces as definition

### ISSUE THREAD

**Issue by JesperTreetop** [tree-sitter/tree-sitter-c-sharp#135]
(This refers to the [GitHub feature](https://github.blog/changelog/2020-10-19-code-navigation-for-c-repositories/) powered by this library.)

See [`ConsList<T>`](https://github.com/dotnet/roslyn/blob/b02627bec02ae2c75d254cb4bbbc14434367b764/src/Compilers/Core/Portable/InternalUtilities/ConsList%601.cs#L23) in Roslyn.

Click on `IEnumerator<T>` in the struct definition. As of this writing, the third found definition [is a test method that happens to be named `IEnumerator`](https://github.com/dotnet/roslyn/blob/b02627bec02ae2c75d254cb4bbbc14434367b764/src/ExpressionEvaluator/CSharp/Test/ResultProvider/ResultsViewTests.cs#L313).

Additionally, the [other](https://github.com/dotnet/roslyn/blob/b02627bec02ae2c75d254cb4bbbc14434367b764/src/Compilers/Test/Resources/Core/NetFX/Minimal/mincorlib.cs#L77) two [definitions](https://github.com/dotnet/roslyn/blob/b02627bec02ae2c75d254cb4bbbc14434367b764/src/Compilers/Test/Resources/Core/NetFX/aacorlib/aacorlib.v15.0.3928.cs#L105) are interfaces without type parameters, and shouldn't show up either.

**Comment by damieng** [comment]
@maxbrunsfeld is this a limitation of the name matching when generics are involved?

**Comment by maxbrunsfeld** [comment]
This is a limitation of GitHub's current "fuzzy" symbol matching system. We are just finding references and definitions, and matching them up by name. We do categorize them (e.g. mark them as "class" or "method", etc), but the category just affects their presentation in the UI; it isn't used in the matching logic.

We are working on more sophisticated code navigation system that models name binding and data flow more precisely, while still meeting our scalability requirements, but we don't have anything ready to show. yet.

For reference @JesperTreetop - the fuzzy code navigation is implemented by this Tree Query: [queries/tags.scm](https://github.com/tree-sitter/tree-sitter-c-sharp/blob/7e9e4c13ceddbe079b039229e9cc937681160602/queries/tags.scm#L1-L36.).

**Comment by damieng** [comment]
Are there any plans @maxbrunsfeld to support namespaces?

In C# we can build up the namespaces and qualifications for the context of names as we go on the definition side through `namespace` (can be nested) - plus also knowing what namespaces are currently "in-scope" via `using` (can be per-file or itself embedded in a namespace or class definition). Could help with narrowing down the possible matches even if it just does something simple like considers the name to be "MyNameSpace.Something.MyClass" rather than just "MyClass".

**Comment by JesperTreetop** [comment]
Impressively responsive!

For further context: I understand that showing the right `IEnumerator<T>` is basically black magic since something might run on various versions of Mono, .NET Framework, CoreCLR or even .NET Standard where it's open-ended. For an interface it doesn't mean a lot of difference, but if it had been a base class it would have made a difference. I don't expect that a GitHub solution or a library like this should be able to resolve this and pick the right version - that takes reading csproj files or implementing half of MSBuild. Maybe if it had been a Microsoft-labeled product built with Roslyn those would be reasonable expectations.

The intent behind the issue is just to say that the things that are recommended shouldn't be used as the definition. I've seen the current GitHub system work well for navigating a Go codebase, where I could jump back and forth with precision. But then again, Go has packages/modules but not the same depth or nesting in namespaces, and doesn't have nominal typing to begin with.

Tracking the namespace sounds promising but does require a whole lot of tracking (aliases, using static and so on). If you have `using static A; using static B; C.C();`, you don't know just from the file alone which namespace the class `C` is from.

**Comment by damieng** [comment]
In the final case you mention there unlike a compiler I don't think we need to be 100% sure what it is - in the case of ambiguity it can probably just offer suggestions. The intent is (I believe, I do not speak for GitHub or the Semantic team) is to provide usefulness not 100% completeness.  

I would also not expect it to resolve IEnumerator<T> to something you can use to "go to definition" as the source for that is outside the repo in question. It's much more useful for navigating around your own code base.

**Comment by JesperTreetop** [comment]
Just to be extra clear: I didn't expect it to throw you to the framework API/sources/documentation for `IEnumerator<T>` and similar framework/system-provided libraries, so this is not a feature request for that. I agree that's not necessary for the purpose of the tool, which is to jump around the code base you're currently in. But I thought there was some sort of hardcoded extra mapping when I saw that I could go to `IEnumerator<T>` and was curious where it would lead which is why I clicked it. 

To be able to provide it for any class/interface/method outside the code base, you'd basically have to build in or otherwise replicate most of Roslyn, MSBuild and NuGet to resolve every factor, and I assume this is outside the scope of this project, to put it mildly.

Matching the arity of generic parameter lists and the type of symbol (where decipherable, absent `using static` shenanigans and the like) seems a lot more achievable which is why I filed the issue. Even if the current Tree Query engine to do the search isn't tuned for this type/style of metadata, it works very well in many languages and is certainly impressive engineering from something that's just there on a web page.

**Comment by maxbrunsfeld** [comment]
I am hopeful that our next iteration (which we're thinking about as "precise code nav") will be able to resolve for 80% - 90% of  C# symbols accurately, by modeling things like namespaces, classes, inheritance, interfaces, data-flow within methods, etc. But as you point out, there are certain things that only Roslyn will ever be able to do.

**Comment by damieng** [comment]
I don't think there's anything else for us to do here - it looks like work will continue upstream and I'm sure they'll let us know if we need to tweak/annotate anything to light up.
