### ISSUE TITLE
Is a member binding expression really an expression in C#?

### ISSUE THREAD

**Issue by Sjord** [tree-sitter/tree-sitter-c-sharp#138]
A member binding expression looks [like this](https://github.com/tree-sitter/tree-sitter-c-sharp/blob/master/grammar.txt#L831):

```csharp
.something
```

This is a [valid expression](https://github.com/tree-sitter/tree-sitter-c-sharp/blob/master/grammar.txt#L650) according to the grammar, but I don't think it is.

It's used in [conditional access expression](https://github.com/tree-sitter/tree-sitter-c-sharp/blob/master/grammar.txt#L729) (`a?.b`). The grammer pretends that any expression can follow the `?`, but only a member access or array access can.

So presumably, the same is true for [array access](https://github.com/tree-sitter/tree-sitter-c-sharp/blob/master/grammar.txt#L745). `[1]` would be a valid statement according to this grammar, while I think it shouldn't be.

**Comment by Sjord** [comment]
See also #131.

**Comment by damieng** [comment]
That particular file comes from the Roslyn GitHub repo and was used to guide development. There's definitely a few places we've needed to deviate because of the differences between the parsers or to be more strict/less strict in places as appropriate (e.g. we want to handle fragments of code).

This may well be another place we need to deviate.

**Comment by damieng** [comment]
https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#null-conditional-operator might be a better approach to take for this feature - the problem however with going with the official C# grammar specification is unlike Roslyn it's stuck at C# 6.0 so any features since then that have changed the semantics have to be considered.

**Comment by patrickt** [comment]
Yeah, @maxbrunsfeld and I observed this; it seems to be an artifact both of the original Roslyn grammar and various layers of compromises made to express the Roslyn grammar in tree-sitter.

**Comment by maxbrunsfeld** [comment]
I agree this structure is confusing and weird. I wouldn't mind diverging from Roslyn a bit on this issue; we might be able to shrink the parser a bit if we modeled conditional access expressions more specifically.

**Comment by damieng** [comment]
Okay, I have a fix incoming for this that also solves #131. It doesn't add any new conflict rules and actually drops the Roslyn file parsing issues from 27 files to 25 and does not introduce any new example failures. PR in a few minutes.

**Comment by damieng** [comment]
Merged in, somebody at GitHub will need to do the magic at their end in order to pickup latest changes.

**Comment by Sjord** [comment]
Thanks for the quick follow-up!

**Comment by Sjord** [comment]
I now better understand how conditional access expressions (`a?.b`) are parsed in Roslyn, and why a member binding expression (`.something`) was an expression. Of course `.something` is not a valid expression in itself, but it is used in many things that take an expression.

`a?.b()` only performs the invocation on `b` if `a` is not null, so it's parsed like `a?(.b())`. This means that the parse tree looks like this:

* conditional_access_expression
  * identifier
  * invocation_expression
    * member_binding_expression
    * argument_list

As you see, the `member_binding_expression` is moved down into the `invocation_expression`. `invocation_expression` consists of an invocation on any expression, and here it invokes a `member_binding_expression`, so `member_binding_expression` should be a type of expression.

This also means that (in Roslyn), the right part of the conditional_access_expression can be many things, not only a member_binding_expression. So that is why the right arm of the conditional_access_expression could contain any expression.
