### ISSUE TITLE
Add ref_type

### ISSUE THREAD

**Issue by damieng** [tree-sitter/tree-sitter-c-sharp#14]
The `_type` in grammar.js does not yet include [ref_type](https://github.com/tree-sitter/tree-sitter-c-sharp/blob/master/grammar.txt#L371) because it causes a conflict with the `ref` keyword modifier.

**Comment by initram** [comment]
We could also just leave out ref_type as we currently parse it as a modifier, unless we want to give some special meaning to ref types compared to other modifier uses. 

See corpus/type-fields.txt "Ref readonly" test. This could be parsed as today:
(modifier) (modifier) (identifier)
Or with ref_type:
(ref_type (identifier))

**Comment by damieng** [comment]
If there are no cases we're missing with the current code I think we can close this issue - I can't think of a reason we'd want to detect/give it special meaning compared to the modifer.
