### ISSUE TITLE
Array member access is parsed as array type

### ISSUE THREAD

**Issue by Sjord** [tree-sitter/tree-sitter-c-sharp#141]
I have a program like this:

```csharp
string[] a = { "hello", "world" };
Console.WriteLine(a[1].Length);
```

I expect the `a[1]` to be parsed as an element access expression, but instead it's parsed as array type.

**Comment by damieng** [comment]
Confirmed. This happens when performing a member access upon an array item. 

Minimal repo is

```csharp
var g = args[0].Length;
```

Which *should* generate

```
(compilation_unit
  (global_statement
    (local_declaration_statement
      (variable_declaration (implicit_type)
        (variable_declarator (identifier)
          (equals_value_clause
            (member_access_expression
              (element_access_expression
                (identifier)
                (bracketed_argument_list (argument (integer_literal))))
            (identifier))))))))
```

I think this is a regression introduced in 57ba56f25b415da5b3dd2e7381387fa99d71b314 and I have a fix I'll create a PR for shortly.
