### ISSUE TITLE
Incorrect precedence with is and as

### ISSUE THREAD

**Issue by Sjord** [tree-sitter/tree-sitter-c-sharp#150]
```csharp
var a = new object() is null as Object;
```

Actual: `new object() is (null as Object)`
Expected: `(new object() is null) as Object`

**Comment by Sjord** [comment]
Correct:

* var a = 1 is int as object;
* var a = 1 is int x as object;
* var a = b is int as object;

Incorrect:

* var a = b is null as Object;
* var a = b is null as object;
* var a = 1 is 3 as object;

These incorrectly parsed pieces all have a `constant_pattern` with an `as_expression` in them:

```
          (equals_value_clause
            (is_pattern_expression
              (identifier)
              (constant_pattern
                (as_expression
                  (null_literal)
                  (identifier))))))))))
```

The grammar for `constant_pattern` seems problematic. It current allows any expression, even though it [only should allow constants](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/patterns#constant-pattern). Also, changing the precedence of the expression seems incorrect.

```javascript
constant_pattern: $ => prec.right($._expression),
```

Test:

```
=====================================
Precedence between is operator and as operator
=====================================

var a = new object() is null as Object;

---

(compilation_unit
  (global_statement
    (local_declaration_statement
      (variable_declaration
        (implicit_type)
        (variable_declarator
          (identifier)
          (equals_value_clause
            (as_expression
              (is_pattern_expression
                (object_creation_expression
                  (predefined_type)
                  (argument_list))
                (constant_pattern
                  (null_literal)))
              (identifier))))))))
```

**Comment by initram** [comment]
One of the problems with constant_expression is that it actually allows any expression that can be evaluated at compile time. (see https://github.com/dotnet/csharplang/blob/main/spec/expressions.md#constant-expressions)

`var test = "ab" is "a" + "b";`

Here "a" + "b" is a constant pattern that matches "ab".
