### ISSUE TITLE
Incorrect precedence between switch and multiplication

### ISSUE THREAD

**Issue by Sjord** [tree-sitter/tree-sitter-c-sharp#153]
```csharp
        var b = 2 * a switch
        {
            1 => 1,
            _ => 0,
        };
```

Expected: `2 * (a switch ...)`
Actual: `(2 * a) switch ...`

**Comment by damieng** [comment]
Maybe one issue with the various examples will suffice.

**Comment by damieng** [comment]
Okay, it seems while some of these are related others are not (e.g. null coalesce).
