### ISSUE TITLE
Tuple pattern parsed as tuple expression in simple assignment

### ISSUE THREAD

**Issue by Sjord** [tree-sitter/tree-sitter-c-sharp#165]
```csharp
    public static void Main()
    {
	int x;
        (x, _) = (3, 4);
    }
```

Here `(x, _)` is a tuple pattern. It is incorrectly parsed as a tuple expression. `_` is incorrectly parsed as identifier instead of as discard.

          (expression_statement [5, 8] - [5, 24]
            (assignment_expression [5, 8] - [5, 23]
              left: (tuple_expression [5, 8] - [5, 14]
                (argument [5, 9] - [5, 10]
                  (identifier [5, 9] - [5, 10]))
                (argument [5, 12] - [5, 13]
                  (identifier [5, 12] - [5, 13])))
              (assignment_operator [5, 15] - [5, 16])
              right: (tuple_expression [5, 17] - [5, 23]
                (argument [5, 18] - [5, 19]
                  (integer_literal [5, 18] - [5, 19]))
                (argument [5, 21] - [5, 22]
                  (integer_literal [5, 21] - [5, 22]))))))))))

**Comment by Sjord** [comment]
Roslyn parses this the same way, which makes me less sure this is a bug in tree-sitter-c-sharp.

**Comment by damieng** [comment]
Confirmed that this looks the same as Roslyn in VS 2019.

Without more understanding why I don't think we'd want to deviate.

**Comment by Sjord** [comment]
It's possible to assign to `_` if its declared as variable:

        int x;
        int _;
        (x, _) = (3, 4);
        Console.WriteLine($"x: {x}"); // outputs: 3
        Console.WriteLine($"_: {_}"); // outputs: 4

In this case, it seems parsing this as a tuple expression is correct. So it seems up to symbol resolution to determine whether `_` is a variable or a discard. Interesting, but not a bug.

**Comment by damieng** [comment]
Yeah, it's definitely unusual - Roslyn does a lot more than just the parsing we can do when looking at files individually.
