### ISSUE TITLE
Impossible pattern in highlights query

### ISSUE THREAD

**Issue by Sjord** [tree-sitter/tree-sitter-c-sharp#177]
The tests give an error about the highlights. E.g. [when running tree-sitter test](https://github.com/tree-sitter/tree-sitter-c-sharp/runs/2183625601?check_suite_focus=true#step:6:312):

> tree-sitter: src/./query.c:1236: ts_query__analyze_patterns: Assertion `exists' failed.

Locally, my newer tree-sitter gives the following error:

> Query error at highlights.scm:231. Impossible pattern:
> `(type_parameter_constraint (identifier) @type)`

**Comment by Sjord** [comment]
I guess the problem is that there is no `identifier` in a `type_parameter_constraint`. Should this be `type_parameter_constraints_clause` instead of `type_parameter_constraint`? @jcs090218, can you look into this?

**Comment by damieng** [comment]
I've removed that line for now but for me the main error was the multi-match specifier on prefix_unary so I've changed that too for now. I need to setup something where I can check the syntax highlighting locally and dig into the syntax.

PR is at #180

**Comment by maxbrunsfeld** [comment]
You should be able to test the highlights at the command line by running ‘tree-sitter highlight  some-file’. I think this works on windows, but I haven’t actually tested it.
