### ISSUE TITLE
Add xml doc comment parsing

### ISSUE THREAD

**Issue by damieng** [tree-sitter/tree-sitter-c-sharp#18]
There is a lot of XML specified in the grammar.txt but it is not clear if/how it ties in with the `///` commenting (there is no pattern for `///` listed)

**Comment by amaanq** [comment]
This should be done via injections - this is similar to rust's doc comments where it can contain markdown, so with c# containing xml in its doc comments it should inject using the [xml parser](https://github.com/tree-sitter-grammars/tree-sitter-xml)

Injections are handled however downstream projects want to handle them, so this isn't really actionable here
