### ISSUE TITLE
Preprocessor directives don't interpret escape sequences

### ISSUE THREAD

**Issue by Sjord** [tree-sitter/tree-sitter-c-sharp#188]
```cs
#line 200 "C:\test\new\user.cs"
```

Expected:

```
(compilation_unit [0, 0] - [0, 31]
  (preprocessor_call [0, 0] - [0, 31]
    (preprocessor_directive [0, 0] - [0, 5])
    (integer_literal [0, 6] - [0, 9])
    (string_literal [0, 10] - [0, 31])))
```

Actual:

```
(compilation_unit [0, 0] - [0, 31]
  (preprocessor_call [0, 0] - [0, 31]
    (preprocessor_directive [0, 0] - [0, 5])
    (integer_literal [0, 6] - [0, 9])
    (string_literal [0, 10] - [0, 31]
      (escape_sequence [0, 13] - [0, 15])
      (escape_sequence [0, 18] - [0, 20])
      (ERROR [0, 22] - [0, 30]
        (ERROR [0, 22] - [0, 24])))))
foo.cs	0 ms	(ERROR [0, 22] - [0, 30])
```

In C# strings, escape sequences such as `\t` for tab and `\n` for newlines can be used. However, no such escape sequences exist in preprocessor directives. For example, the following will report an error on `C:\test\new\program.cs` and not on `C:[tab]est[newline]ew\user.cs`.

```
#line 200 "C:\test\new\user.cs"
var a = ;
```

```
$ dotnet build
...
C:\test\new\user.cs(200,17): error CS1525: Invalid expression term ';' 
```

According to tree-sitter, a `preprocessor_call` can contain a `_literal`, which can be a `string_literal`, which can contain an `escape_sequence`.

**Comment by damieng** [comment]
I'll take this one if you haven't started on a fix.

**Comment by damieng** [comment]
I have a fix for this particular case but I found another we're failing on;

```csharp
#if a==true
```

I think the best thing here is if I go ahead and grammar out the preprocessor instructions properly as per #16 to ensure we've got all the cases covered - I think https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives is the definitive list.

**Comment by damieng** [comment]
I am almost ready to go with the PR on this - just optimizing the `#if` conditionals so that `||` and `&&` behave like C#.
