### ISSUE TITLE
Enable recursive_pattern rule (for positional and property patterns)

### ISSUE THREAD

**Issue by damieng** [tree-sitter/tree-sitter-c-sharp#19]
The Roslyn grammar.txt defines `recursive_pattern` as:

```antlr
recursive_pattern
  : type? positional_pattern_clause? property_pattern_clause? variable_designation?
```

Which means everything is optional.  You can't do that in tree-sitter so need an alternative.

**Comment by initram** [comment]
I am working on this, but there are still some kinks to work out to avoid too many conflicts.
