### ISSUE TITLE
Consistency in delegates

### ISSUE THREAD

**Issue by pollen00** [tree-sitter/tree-sitter-c-sharp#218]
I'm not quite sure if it's possible to do this with custom queries and I just missed it, but from what I can tell it's not possible to have consistency with delegate coloring. 

It should be possible to color delegates in all contexts (declaration, usage, calls) the same color.

![image](https://user-images.githubusercontent.com/36719558/154898367-eb2dec15-c50f-46e4-9703-e89e781bcbb3.png)

![image](https://user-images.githubusercontent.com/36719558/154898375-2200afa8-c735-4604-9381-9673263aad28.png)

**Comment by damieng** [comment]
tree-sitter-c-sharp makes no judgement on coloring - can you provide more detail as to what selectors you think are missing or mismatched?

**Comment by pollen00** [comment]
What I was trying to say is that delegates should have queries in various contexts (not sure if that's what they're called, but the things in highlights.scm).

So basically I just want the ability to assign delegates in every context to the same highlight group.

Sorry if this isn't coming off very clear 😃 .

**Comment by pollen00** [comment]
Oh, sorry I didn't realize. I was using neovim + nvim-treesitter.

To put it the best way I can, things in queries/highlight.scm that are for the different circumstances delegates occur in.

So for example:
delegate_declaration
delegate_call
delegate_param

or something like that. Similar to the split between variable declaration and declarator.

**Comment by damieng** [comment]
You have to remember that tree-sitter grammars are just that - grammars. 

They are not compilers.

It is not possible for tree-sitter to resolve references - that requires a complete type system such as a compiler will have.
