### ISSUE TITLE
c# 11 raw string literals

### ISSUE THREAD

**Issue by kasperk81** [tree-sitter/tree-sitter-c-sharp#222]
per [docs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated), these are valid and invalid cases starting with c# 11
```c#
// valid
x = $"""The point "{X}, {Y}" is {Math.Sqrt(X * X + Y * Y)} from the origin""";
x = $"""The point ""{X}, {Y}"" is {Math.Sqrt(X * X + Y * Y)} from the origin""";
x = $""""The point """{X}, {Y}""" is {Math.Sqrt(X * X + Y * Y)} from the origin"""";
x = $$"""The point {{{X}}, {{Y}}} is {{Math.Sqrt(X * X + Y * Y)}} from the origin""";

// invalid
x = $"The point "{X}, {Y}" is {Math.Sqrt(X * X + Y * Y)} from the origin";
x = $""The point ""{X}, {Y}"" is {Math.Sqrt(X * X + Y * Y)} from the origin"";
x = $"""The point """{X}, {Y}""" is {Math.Sqrt(X * X + Y * Y)} from the origin""";
x = $$"""The point {{X}, {{Y}}} is {{Math.Sqrt(X * X + Y * Y)}} from the origin""";
```

also take a look at 'what's new in c# 11' series: https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-11#raw-string-literals

tree-sitter doesn't handle valid cases.

**Comment by damieng** [comment]
I'm planning on tackling the C# 11 features next week :)

**Comment by kasperk81** [comment]
cool. we still have time until november when c# 11 will officially released (as part of .net 7 release). using preview 3 of .net 7 let us play with it.

here is another one "utf-8 string literals" (https://github.com/dotnet/csharplang/blob/main/proposals/utf8-string-literals.md)

following five are equal:
```c#
byte[] utf8String;

utf8String = new byte [] { 97, 98, 99 };

utf8String = new byte [] {
    (byte)'a', (byte)'b', (byte)'c' };

// new in c# 11
utf8String = "abc";
utf8String = "abc"u8; // tree-sitter has issue with the new 'u8' suffix
utf8String = "abc"U8; // tree-sitter has issue with the new 'U8' suffix
```
`u8` suffix name is case insensitive like other constant suffix (f/F for float, d/D for double and m/M for decimal)

**Comment by damieng** [comment]
I think the `u8` stuff is still up in the air - neither of those u8 suffixes work in the latest bits.

**Comment by kasperk81** [comment]
i am using preview 4 (second column https://github.com/dotnet/installer#table) with `<LangVersion>Preview<LangVersion>` in csproj.

**Comment by damieng** [comment]
Just updated to preview 4 and still having the same issue. I'm going to leave utf-8 support for now until things are further along.

**Comment by kasperk81** [comment]
ok. for reference, i can run it locally with daily build (first column from installer table) and here is an example running on [sharplab](https://sharplab.io/#v2:EYLgtghglgdgPsAngFwKYG0C6ACArsgMwA4BlZAJ1gHMBuAWAChH9izKYrsBebGVAd2xI02LNgDe2AJwB2ADTSiCqVOwBfekwYtSFat14ChKVKJzjG2K9gAUw1AEoA5BCcK7J58De37zgMZO6pqMAPShhoKw2P4AxNgAjAnMhLrsnDwARBDA/pmaOmz6WTl5uEQ02OHYFKioALQAzlDIaOTYABYQjdhQjY24pvwtHTUdpnyCTuVBAwQEUAAeKax6HAbZuZkAqhVVEbUNza2o7V09fQNDI2MTRk67s7jzS0A=).
