### ISSUE TITLE
C# 11.0 feature support

### ISSUE THREAD

**Issue by damieng** [tree-sitter/tree-sitter-c-sharp#223]
Issue to track the various parts of C# 11 support - currently in preview so subject to change before then.

Some C# 11 syntax works already as we are not as strict as Roslyn, specifically:

- [x] Generic attributes
- [x] Static abstract interface methods
- [x] Newlines in interpolated strings

Some remaining support is required for:

- [x] List patterns
- [x] Slice patterns
- [ ] Raw string literals #222

**Comment by initram** [comment]
I think you missed "required members" which adds a new contextual keyword to member declarations.
See https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-11

**Comment by damieng** [comment]
Thanks for the reminder @initram  - included it with this PR now so should all be good.
