### ISSUE TITLE
Code Fences Language Identifier

### ISSUE THREAD

**Issue by pleor** [tree-sitter/tree-sitter-c-sharp#228]
In order to get highlighting to work with C# in markdown, the language identifier must be _c_sharp_.

I have tried:

```lua
local ft_to_parser = require"nvim-treesitter.parsers".filetype_to_parsername
ft_to_parser.csharp = "c_sharp" 
ft_to_parser.cs = "c_sharp"
```

But I don't think this was the way that the filetype-to-parser mapping was intended to be used.

**Comment by patrickt** [comment]
This looks like a Neovim-specific issue, and should go to their issue tracker.

**Comment by pleor** [comment]
Why?

It seems to me that because the parser is called _c_sharp_, rather than just _csharp_, we have this problem.

If I do \```c_sharp, everything works. This is not a tree-sitter issue?

**Comment by damieng** [comment]
TreeSitter and tree-sitter-c-sharp have no concept of how it will be used in a markdown editor. It seems that the neovim people decided to map based on the tree-sitter name by default and indeed that does not match.

However changing this now would probably break all current consumers of this package.

**Comment by patrickt** [comment]
Yeah, tree-sitter isn’t in control of how people use editor context to map into different languages. The fact that neovim use the declared tree-sitter name to do that mapping is a result of their implementation, and special-casing name handling like this should be a matter for that code to deal with. The breakage fallout associated with renaming the package and the parser isn’t feasible for us to undergo.
