### ISSUE TITLE
Question: v0.20 release plans

### ISSUE THREAD

**Issue by alp** [tree-sitter/tree-sitter-c-sharp#232]
Thank you for the hard work you are doing for the project. 
Do you have plans to release a version based on tree-sitter 0.20, which has been available for a while? I see that master is already using it, so wanted to check on release plans.

Thanks!

**Comment by damieng** [comment]
Hi Alp.

I'm hoping to get a 0.20 release out in the next day or two.

**Comment by damieng** [comment]
Now published to npm and crates.io - let me know if there are any problems.
