### ISSUE TITLE
Generic methods not highlighted correctly

### ISSUE THREAD

**Issue by musjj** [tree-sitter/tree-sitter-c-sharp#298]
Casting using a generic method is highlighted incorrectly, when it's assigned to a variable.

![image](https://user-images.githubusercontent.com/72612857/221384989-74760bf4-0b8c-46ad-810b-f91672dca8c4.png)

**Comment by damieng** [comment]
Tree-Sitter Grammars do not, themselves, do any syntax highlighting.

What IDE/editor/viewer are you using?

**Comment by musjj** [comment]
Sorry for not being specific, I guess. I'm using neovim, and it seems that problem isn't the highlighting, but the fact that they're not parsed correctly:

![image](https://user-images.githubusercontent.com/72612857/221386083-ffbaeb26-56de-404b-9726-dd24d9d3e7f3.png)
![image](https://user-images.githubusercontent.com/72612857/221386111-17d1f5be-d905-456b-8be2-5c3893e76903.png)

![image](https://user-images.githubusercontent.com/72612857/221386123-34c39a8d-4347-4ea3-813c-8bcf11020d41.png)
![image](https://user-images.githubusercontent.com/72612857/221386147-0f2f0828-5ffc-43fa-8812-da5775fa7dc1.png)

**Comment by damieng** [comment]
Your block of code parses as:

```
  (compilation_unit
      (global_statement
        (local_declaration_statement
          (variable_declaration
            (identifier)
            (variable_declarator
              (identifier)
              (equals_value_clause
                (invocation_expression
                  (generic_name
                    (identifier)
                    (type_argument_list
                      (identifier)))
                  (argument_list
                    (argument
                      (string_literal)))))))))
      (global_statement
        (expression_statement
          (invocation_expression
            (generic_name
              (identifier)
              (type_argument_list
                (identifier)))
            (argument_list
              (argument
                (string_literal)))))))
```
So both of them are mapping to the exact same block during the parsing phase. I checkout our tagging system which is used by highlighters as well:

![image](https://user-images.githubusercontent.com/118951/221401432-61adf49a-bc92-4ae5-8e15-9e788a769986.png)

While I'm not familiar with NeoVIM I would suggest trying to disable OmniSharp to see if the syntax on first then matches the syntax on the second.

**Comment by musjj** [comment]
I've turned of the LSP, but no luck.
![image](https://user-images.githubusercontent.com/72612857/221406238-d5ecfdc7-48a5-492c-934b-ac62a1bbb2a9.png)
Weirdly, it seems that it got parsed as a binary expression for me. I wonder if my parser is outdated or something...

**Comment by damieng** [comment]
That's very strange - its basically not detecting that GetNode has a generic type and instead is somehow treating this as a `>` or `<` operation (hard to tell from that tree). Looking at your original screenshot I can now see that the `<` and `>` symbols are treated differently in both cases.

Not sure what to suggest, I can't repro this with tree-sitter-c-sharp and even if they are using an old-version I don't recall any version that got confused in this way.

**Comment by damieng** [comment]
I've found this - it seems to be a very recent regression, let me investigate.

**Comment by damieng** [comment]
Regression introduced in https://github.com/tree-sitter/tree-sitter-c-sharp/pull/294 which also shows a lack of these use cases in the corpus tests.

**Comment by damieng** [comment]
Should now be working correctly here - neovim-tree-sitter will need to update their reference to the latest commit on master.

**Comment by musjj** [comment]
Thanks a lot for the swift response! I'll give it a go once they bumped up the commit in the repo.

**Comment by musjj** [comment]
This is fixed now, thanks a lot!
