### ISSUE TITLE
Highlight members within a class differently than local variables

### ISSUE THREAD

**Issue by rudiejd** [tree-sitter/tree-sitter-c-sharp#325]
Minimal example: 

```csharp
class Example {
    private readonly int _member;
    public Example(int member) {
        _member = member;
    }
}
```

We should have some way to highlight the members within the member assignment differently than we highlight the other local variables (for example, the member argument to `Example` default constructor.

highlighting in neovim using this parser:
![image](https://github.com/tree-sitter/tree-sitter-c-sharp/assets/46619169/19fe38d0-6659-489d-bee2-443ebc32103e)

highlighting in jetbrains rider:
![image](https://github.com/tree-sitter/tree-sitter-c-sharp/assets/46619169/1a442ccf-c1cb-4e51-b111-146515241978)

**Comment by damieng** [comment]
tree-sitter-c-sharp is just a parser - we tokenize the language keywords. These are all just identifiers to us as per the C# Language Specification. We can't know if `_member` is a variable, parameter, instance variable etc. without a compilation model.

That is well beyond the scope tree-sitter and indeed any C# parser and off into compiler territory. To get that you'd need to switch to a language server with a real compiler.
