### ISSUE TITLE
Parse error classes with  primary constructors (C#12, Dotnet 8 LTS)

### ISSUE THREAD

**Issue by neuromagus** [tree-sitter/tree-sitter-c-sharp#329]
https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/primary-constructors

Tree-sitter did not understand ```record class``` with ```primary constructor``` syntax. 
Perhaps this behavior extends to structures.

![20240409_01h13m21s_grim](https://github.com/tree-sitter/tree-sitter-c-sharp/assets/63796667/2d2f698d-175b-4949-b211-b424b8bfe124)

P.S. Please, don't ask me about theme, I try to config nvim ;} How to get out?

**Comment by neuromagus** [comment]
I understand for this

>C# 12.0 (under development)

but all plugins, which use tree-sitter work with UB. For example, [this](https://github.com/nvim-treesitter/nvim-treesitter-context) et cetera... (The Emacs universe - is another question).
I read the code a little, and... Guys!.. C#, complicated by syntactic sugar compared to Java, but parser.c in 42Mb and 2.5Mb? So Csharp syntax is 16 times heavier?

I understand, DSL, Dotnet updates every year. If u have any instructions for learn this DSL and/or normal realized examples - i'm in. I have a time to help. IMHO, maybe it’s worth creating a coherent structure and describing it in the documentation? The language is in good shape, developing well, transition to FP is underway, syntax and new constructions will be added constantly.

P.S. Sorry for my English.

**Comment by tamasvajk** [comment]
https://github.com/tree-sitter/tree-sitter-c-sharp/issues/273#issuecomment-1378967268 references a commit that increased the parser size significantly.
