### ISSUE TITLE
Support primary constructor

### ISSUE THREAD

**Issue by juli1** [tree-sitter/tree-sitter-c-sharp#332]
The current grammar does not support [primary constructors](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/primary-constructors). We should support primary constructors.

**Comment by neubaner** [comment]
I have been working on primary constructors support in my [fork](https://github.com/neubaner/tree-sitter-c-sharp/tree/primary-constructors). Still WIP and there's a lot of tests missing, but hopefully I can submit a PR soon!
