### ISSUE TITLE
Python binding for tree-sitter-c-sharp does not work correctly

### ISSUE THREAD

**Issue by Pstva** [tree-sitter/tree-sitter-c-sharp#351]
The error is obtained when trying to get language and then to use it in tree_sitter.Language():

```python
from tree_sitter import Language
import tree_sitter_c_sharp

Language(tree_sitter_c_sharp.language())
```

Error: TypeError: an integer is required

It seems that the problem is that `tree_sitter_c_sharp.language()` is not an integer (like the output in bindings for other languages) but some PyCapsule object. 

tree_sitter_c_sharp=="^0.23.0"
tree-sitter=="^0.22.3"
Python 3.10.12; Ubuntu 22.04

**Comment by amaanq** [comment]
Upgrade py-tree-sitter.

**Comment by Pstva** [comment]
upgraded, now both py-tree-sitter and tree-sitter-c-sharp have versions '0.23.0'

But the error is still there

**Comment by amaanq** [comment]
Well, it works for me, so I'm guessing it's not actually upgraded. Post the output of `pip show tree-sitter`.

<img width="687" alt="image" src="https://github.com/user-attachments/assets/b4b4a55e-e749-49d2-8558-e9b16e9926d9">
