### ISSUE TITLE
Identifier regex should match non-ascii letter characters

### ISSUE THREAD

**Issue by initram** [tree-sitter/tree-sitter-c-sharp#37]
Language spec for identifiers can be found here:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/lexical-structure#identifiers

I have not been able to change the regex to use unicode caracter classes though, as I get the following error when I try:
`Regex error: Unsupported character class syntax Unicode(ClassUnicode { span: Span(Position(o: 15, l: 1, c: 16), Position(o: 24, l: 1, c: 25)), negated: false, kind: Named("Lu") })`

Is there a way to support unicode character classes?

**Comment by maxbrunsfeld** [comment]
Tree-sitter doesn't support unicode categories like `Lu` right now. I'd like to add support, but it'll take significant work. For now, I would recommend just using a regex that captures most of the non-ascii characters that you see in practice. That's what we [do in `tree-sitter-go`](https://github.com/tree-sitter/tree-sitter-go/blob/85165cbb4430a377473d7e04dd1c37ea2578afd5/grammar.js#L18) for example.
