### ISSUE TITLE
Support logical operators in pattern matching

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/tree-sitter-c-sharp#68]
C# 9.0 added `and`, `or` and `not` statements in pattern matching: https://github.com/dotnet/csharplang/issues/2850

This feature is present in dotnet/roslyn:
```csharp
            if (obj is not WorkspaceKindMetadata metadata)
                return false;
```

**Comment by damieng** [comment]
Do we want to use the "bug" tag for C# 9 support? It was ratified only recently. If we do any analysis in the future it might be nicer to break out what we thought was in but broken vs what C# added and we were playing catch-up?

**Comment by patrickt** [comment]
@damieng I don’t have strong feelings—maybe @maxbrunsfeld does—but IMO this grammar should be able to parse as much of `dotnet/roslyn` as is possible.

**Comment by damieng** [comment]
So just as a heads up C# 9.0 isn't actually released until November with the release of .NET 5.0.

I agree we should add support - just wanted to clarify it's not a bug in the traditional sense - it's supporting new cutting-edge syntax.

**Comment by damieng** [comment]
One further point to make here - `donet/roslyn` is probably unique in that it is the only significantly-sized repo that is using C# 9.0 at this point in time.
