### ISSUE TITLE
Support destructuring tuple assignment

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/tree-sitter-c-sharp#69]
We currently fail on code like this:
```csharp
foreach (var (document, diagnosticsForDocument) in diagnostics.GroupBy(d => GetReportedDocument(d, treeToDocumentMap)))
```

Changing that `(document, diagnosticsForDocument)` pattern to a single binding removes the error, so I think this is probably some new syntax. I don’t know what it’s called, though; I’ll need a C# expert’s take here.

**Comment by maxbrunsfeld** [comment]
We already have a `tuple_pattern` rule that we use to handle the equivalent binding in a regular declaration, so I'm guessing we can reuse that here:

https://github.com/tree-sitter/tree-sitter-c-sharp/blob/2404a6987eefa11f1b391250fffc5e82edf0edf3/grammar.js#L213-L231

**Comment by patrickt** [comment]
Changed the title to reflect this, as I’ve found it happens outside of foreach loops too:
```csharp
var (instance, (node, _)) = nodePair;
```

**Comment by maxbrunsfeld** [comment]
Ah yeah, it looks like `tuple_pattern` needs to allow *other* tuple_patterns as children.
