### ISSUE TITLE
How to tell what is missing

### ISSUE THREAD

**Issue by Benjamin-Davies** [tree-sitter/tree-sitter-c-sharp#7]
Is there a list or other easy way to identify aspects that are missing?

Perhaps we need a checklist so that we can know when the project is "complete".

**Comment by damieng** [comment]
What's missing is everything that's in grammar.txt that is not in grammar.js.  Maintaining a separate list at this stage would be a non-trivial amount of work that would detract from doing the work.  

Might be worth putting a list up though once we're closer and the remaining work is harder to do.
