### ISSUE TITLE
Add support for property patterns

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/tree-sitter-c-sharp#72]
As per [this](https://devblogs.microsoft.com/dotnet/do-more-with-patterns-in-c-8-0/#property-patterns) blog post (hattip @maxbrunsfeld), we need to support property patterns, which query accessible properties/fields of structures.

```csharp
if (initializer is { Parent: { } })
```

**Comment by patrickt** [comment]
Looks like there’s some prior attempts at this in the code: this rule takes a stab at implementing [this syntax description](https://github.com/dotnet/csharplang/blob/a17f4c8ba82ed19fdad8b9f86ac151a443c89b08/proposals/csharp-8.0/patterns.md#patterns), but it’s commented out at the use site:

```javascript
    recursive_pattern: $ => seq(
      optional($._type),
      optional($.positional_pattern_clause),
      optional($.property_pattern_clause),
      optional($._variable_designation)
    ),
```

**Comment by damieng** [comment]
There were some areas around patterns that I just couldn't figure out the conflict or associative rules for to get things working - 
I suspect that was one of them.

**Comment by damieng** [comment]
I think this is really a dupe of #19

**Comment by patrickt** [comment]
So it is. Closing in favor of #19.
