### ISSUE TITLE
Support trailing ? in in type parameter constraints

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/tree-sitter-c-sharp#74]
As per [here](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/constraints-on-type-parameters), this is legal syntax for is/descends-from and nullability relations.

Found in

```csharp
public static void ThrowIfNull<T>([NotNull] T value) where T : class?
```

**Comment by damieng** [comment]
More info: Added to C# in 8.0 via proposal https://github.com/dotnet/csharplang/blob/3f901fa3036b852131fc2baa528b781580cb005a/proposals/csharp-8.0/nullable-reference-types.md
