### ISSUE TITLE
Support target-type new expressions.

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/tree-sitter-c-sharp#77]
Right now this fails to parse:

```csharp
        internal static class EnumFormatters
        {
            public static readonly EnumFormatter<AnalysisKind> AnalysisKind = new(value => (int)value, value => (AnalysisKind)value);
        }
```

failing at the `= new(` bit. I think [this](https://github.com/dotnet/csharplang/blob/a17f4c8ba82ed19fdad8b9f86ac151a443c89b08/spec/classes.md#constants) is the relevant piece of syntax.

**Comment by patrickt** [comment]
Note also that we don’t support interpolated strings appearing in declarations like these:
```csharp
private static readonly string s_defaultDocumentPath = @$"Document\Path\{DefaultDocumentName}”;
```

**Comment by patrickt** [comment]
I think this bug is more general than just constant declarators.

**Comment by patrickt** [comment]
Here’s a hack that fixes this:
```diff
diff --git i/grammar.js w/grammar.js
index e6432dd..659783d 100644
--- i/grammar.js
+++ w/grammar.js
@@ -891,6 +891,14 @@ module.exports = grammar({
       field('body', choice($.block, $._expression))
     )),
 
+    direct_new_object_creation_expression: $ => seq(
+      'new',
+      '(',
+      commaSep($._expression),
+      optional(','),
+      ')'
+    ),
+
     anonymous_object_creation_expression: $ => seq(
       'new',
       '{',
@@ -1231,6 +1239,7 @@ module.exports = grammar({
     _expression: $ => choice(
       $.anonymous_method_expression,
       $.anonymous_object_creation_expression,
+      $.direct_new_object_creation_expression,
       $.array_creation_expression,
       $.assignment_expression,
       $.await_expression,
```

**Comment by initram** [comment]
The new without a type is a new C# 9 feature called target-type new expressions. This is the issue for it: https://github.com/dotnet/csharplang/issues/100

So it is simply a new feature, not really a bug in the current syntax.

**Comment by initram** [comment]
> Note also that we don’t support interpolated strings appearing in declarations like these:
> 
> ```cs
> private static readonly string s_defaultDocumentPath = @$"Document\Path\{DefaultDocumentName}”;
> ```

This was a new feature in C# 8, where you can use wither $@"Some string" or @$"Some string": https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#enhancement-of-interpolated-verbatim-strings

I can create a PR to fix this.

**Comment by patrickt** [comment]
@initram Aha! I didn’t even notice that the characters were transposed. Thank you!

**Comment by initram** [comment]
I think this issue can be closed now.
