### ISSUE TITLE
Support `params` keyword over nullable types in property declaration arguments

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/tree-sitter-c-sharp#78]
This fails: 
```csharp
        public TestComposition AddAssemblies(params Assembly[]? assemblies)
            => AddAssemblies((IEnumerable<Assembly>?)assemblies);
```

We have this handled in `parameter_array`, so it’s probably just a matter of calling that.

**Comment by initram** [comment]
I think it is related to the nullable_type rule, and its precedece compared to the parameter_array rule.

it generates this bit of syntax
`(ERROR (nullable_type (parameter_array (array_type (identifier) (array_rank_specifier)))))`

where it should really generate something more along the lines of:
`(parameter_array (nullable_type (array_type (identifier) (array_rank_specifier))))`

also the following parses without issues:
`        public TestComposition AddAssemblies(params Assembly[] assemblies)
            => AddAssemblies((IEnumerable<Assembly>?)assemblies);`
