### ISSUE TITLE
Up-to-date grammar available in Roslyn repo

### ISSUE THREAD

**Issue by petrroll** [tree-sitter/tree-sitter-c-sharp#8]
There's a always up-to-date grammar available in Roslyn repo that. It's not a perfect grammer (see discussion here: https://github.com/dotnet/roslyn/pull/37840 ) but it should be better than what's in specification AoRN

https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/Generated/CSharp.Generated.g4

**Comment by damieng** [comment]
I might consider switching to that later but right now switching grammar would be another setback for no immediate advantage.
