### ISSUE TITLE
Support space before nullable directive

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/tree-sitter-c-sharp#86]
This is really nitpicky, but was found in the Roslyn code:
```
# nullable enable
```

`#nullable enable` works fine.

**Comment by damieng** [comment]
This seems to apply to all pre-processor directives.

**Comment by damieng** [comment]
Will take a second stab at this - first one has been reverted as it caused some regressions around string literals containing `#`.

**Comment by patrickt** [comment]
Yeah, those are tricky—I encountered an `#error` inside a multiline interpolated string, which I don’t think we handle correctly even before this patch

**Comment by damieng** [comment]
I can take on #16 if you want - the structured trivia isn't defined in the formal C# spec so it's really looking at Roslyn and seeing what it does. I normally do that using the Syntax Visualizer in VS with appropriate code fragments which is obviously only a useful strategy if you're on Windows.
