### ISSUE TITLE
Double-brackets in interpolated strings

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/tree-sitter-c-sharp#87]
As found in Roslyn:
```csharp
            var content = $@"
class A
{{
    bool Method(int value)
    {{
        return value  is  {operatorText}  3  or  {operatorText}  5;
    }}
}}
“;
```

Looks like {{ is interpreted as a literal {, and I’m not sure we have rules to handle that yet.

**Comment by patrickt** [comment]
Preprocessor-directive-looking things also fail:
```csharp
            VisualStudio.Editor.SetText(@$"
#error version:{version}
“);
```

**Comment by damieng** [comment]
What is the parse tree from the second one?

Interpolated string is only using the `_expression` block right now which doesn't include the pre-processor. In fact the only thing that includes the pre-processor is the tree-sitter-declared `extras` block.

Do we have any other languages that are allowing interpolated string and preprocessor instructions? Might be worth seeing how they're managing the rules to co-exist.

**Comment by initram** [comment]
> Preprocessor-directive-looking things also fail:
> ```csharp
>             VisualStudio.Editor.SetText(@$"
> #error version:{version}
> “);
> ```

The # should just be treated as text here. Please make sure that the error does not stem from the order of @ and $, that I fixed earlier.
