### ISSUE TITLE
Support keywords as arguments to lambdas.

### ISSUE THREAD

**Issue by patrickt** [tree-sitter/tree-sitter-c-sharp#89]
It surprises me that this works, but it appears to be correct: note that the argument to the lambda is named `var`.

```csharp
var firstVarDeclWithInitializer = variableDeclaration.Variables.FirstOrDefault(var => var.Initializer != null && var.Initializer.Value != null);
```

**Comment by damieng** [comment]
I think this one is a manifestation of #47 but could be wrong.

**Comment by patrickt** [comment]
Yeah, you’re right. Closing.
